### ISSUE TITLE
data.zip is corrupt

### ISSUE THREAD

**Issue by MarkPoolman** [AlexanderKroll/kcat_prediction_function#1]
The data.zip linked here to googledrive can't be unpacked:

$ unzip data.zip 
  Archive:  data.zip
warning [data.zip]:  4409363946 extra bytes at beginning or within zipfile
  (attempting to process anyway)
error [data.zip]:  start of central directory not found;
  zipfile corrupt.
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)

I get an equivalent error when trying to unpack via the file browser.

Help *very* gratefully received!

Mark

**Comment by AlexanderKroll** [comment]
Hi Mark, 

I created a new zip folder, which should now be working.
