### ISSUE TITLE
about the file "xgboost_train_and_test.pkl"

### ISSUE THREAD

**Issue by qqlaoxia** [AlexanderKroll/kcat_prediction_function#2]
You did an excellent job. However, you did not provide the xgboost_train_and_test.pkl file.

**Comment by AlexanderKroll** [comment]
Dear qqlaoxia,

did you download the unzip the data folder from zenodo as described on the readme page? The "xgboost_train_and_test.pkl" file should be in the folder "data\saved_models\xgboost".

**Comment by qqlaoxia** [comment]
The problem has been resolved, thank you very much. Thanks for this powerful tool
