### ISSUE TITLE
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### ISSUE THREAD

**Issue by nkim23nyk6** [AlexanderKroll/kcat_prediction_function#4]
Hello,

Been getting the error below, how do you fix this?

df = kcat_predicton(substrates = substrates,
               products = products,
               enzymes = enzymes)

Step 1/3: Calculating numerical representations for all substrates and products.
Step 2/3: Calculating numerical representations for all enzymes.
.....2(a) Loading ESM-1b model.
.....2(b) Loading model parameters for task-specific model.
.....2(c) Calculating enzyme representations.
Step 3/3: Making predictions for kcat.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-52-f05339395e7a>](https://localhost:8080/#) in <cell line: 1>()
----> 1 df = kcat_predicton(substrates = substrates,
      2                products = products,
      3                enzymes = enzymes)

1 frames
[<ipython-input-14-963972f87275>](https://localhost:8080/#) in merging_reaction_and_enzyme_df(df_reaction, df_enzyme, df_kcat)
     72                 esm1b_rep = list(df_enzyme["enzyme rep"].loc[df_enzyme["amino acid sequence"] == df_kcat["enzyme"][ind]])[0]
     73 
---> 74                 if diff_fp == "" or esm1b_rep == "":
     75                         df_kcat["complete"][ind] = False
     76                 else:

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Thanks in advance,

**Comment by AlexanderKroll** [comment]
Hi, I think this error occurs in newer Python versions. I substituted line 74 with "if isinstance(drfp, str) and isinstance(esm1b_rep, str):". I think this should work for all Python versions. Please let me know if this still doesn't work.

**Comment by nkim23nyk6** [comment]
Hi Alex,

Thanks for updating me on the repository.

I tried executing the code again, but now I get the error below:


Step 1/3: Calculating numerical representations for all substrates and products.
Step 2/3: Calculating numerical representations for all enzymes.
.....2(a) Loading ESM-1b model.
.....2(b) Loading model parameters for task-specific model.
.....2(c) Calculating enzyme representations.
Step 3/3: Making predictions for kcat.

---------------------------------------------------------------------------

NameError                                 Traceback (most recent call last)

<ipython-input-12-f05339395e7a> <https://localhost:8080/#> in <cell
line: 1>()----> 1 df = kcat_predicton(substrates = substrates,      2
              products = products,      3                enzymes =
enzymes)


------------------------------
1 frames
------------------------------

<ipython-input-10-1bb518399671> <https://localhost:8080/#> in
kcat_predicton(substrates, products, enzymes)     31     							
"enzyme" : enzymes, "index" : list(range(len(substrates)))})     32
---> 33     df_kcat = merging_reaction_and_enzyme_df(df_reaction,
df_enzyme, df_kcat)     34     df_kcat_valid, df_kcat_invalid =
df_kcat.loc[df_kcat["complete"]], df_kcat.loc[~df_kcat["complete"]]
 35     df_kcat_valid.reset_index(inplace = True, drop = True)

<ipython-input-10-1bb518399671> <https://localhost:8080/#> in
merging_reaction_and_enzyme_df(df_reaction, df_enzyme, df_kcat)     72
                esm1b_rep = list(df_enzyme["enzyme
rep"].loc[df_enzyme["amino acid sequence"] ==
df_kcat["enzyme"][ind]])[0]     73 ---> 74                 if
isinstance(drfp, str) and isinstance(esm1b_rep, str):     75
              df_kcat["complete"][ind] = False     76
else:

NameError: name 'drfp' is not defined


Any idea why I might be getting this error message?

Thank you so much,

**Comment by AlexanderKroll** [comment]
Sorry, there was a stupid typo in line 74. Can you try it again with the new version?

**Comment by nkim23nyk6** [comment]
Hi Alex,

It's working fine now. Thank you for this amazing tool.

One question, if I have like 20 protein sequences to compare (one
substrate/product pair), do I use semicolons in between protein sequences?
Also, do I need to list the same substrate/product Inchi 20 times if I have
20 protein sequences?

Best,

**Comment by AlexanderKroll** [comment]
Hi, 

I'm glad that it is working now :) 

You would have a list that contains your 20 amino acids as strings separated by commas (e.g. enzymes = ["AAseq1", "AAseq2", ..."AAseq20"]) and the the same for your substrates and products, but for these you would always copy the same entries if you want to keep the same reaction.

**Comment by nkim23nyk6** [comment]
Got it, thank you!

Nam
